config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: "registrations" }
  root 'pages#home'

  resources :subscribers

  resources :profiles do
    collection do
      get :search, :height
    end

    member do
      get :add_language
    end
  end

  resources :messages, only: [ :show, :create, :index] do
    member do
      get :new_reply
    end
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  has_many :sent_messages, class_name: "Message", foreign_key: :sender_id
  has_many :received_messages, class_name: "Message", foreign_key: :recipient_id

  validates :date_of_birth, presence: true
  validates :username, uniqueness: true, presence: true
  after_create :create_profile

  MIN_AGE = 18

  def create_profile
    Profile.create!(:customer => self)
  end

  def gender
    type ? type.downcase : "female"
  end
end

app/models/female.rb
class Female < Customer
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :profile_languages
  has_many :profiles, :through => :profile_languages
end

app/models/male.rb
class Male < Customer
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: "Customer", foreign_key: :sender_id
  belongs_to :recipient, class_name: "Customer", foreign_key: :recipient_id

  belongs_to :responds_to, class_name: "Message", foreign_key: :responds_to_id
  has_one :reply, class_name: "Message", foreign_key: :responds_to_id

  after_create :alert_recipient

  private
  def alert_recipient
    Notifier.new_message(self.recipient, self.sender, self).deliver_now
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  include ProfileCompletedness
  include Conversions::HeightConversions

  geocoded_by :geocode_string
  before_save :geocode, :if => Proc.new { |profile| profile.city_changed? || profile.country_changed? }
  before_save :set_profile_image, :unless => lambda { |o|
    # Only set the image if we have a customer and haven't already got an image
    customer.nil? || o.img_url || o.thumb_url
  }

  has_many :profile_languages
  has_many :languages, :through => :profile_languages
  accepts_nested_attributes_for :profile_languages, :reject_if => proc{ |attrs| attrs[:language_attributes][:name].blank? }

  belongs_to :religion
  belongs_to :customer
  attr_writer :height_feet, :height_inches

  enum education: [ :secondary, :college, :university ]
  enum drinks: [ :Never, :Socially, :Often, :Like_a_fiend]
  enum star_sign: [ :aries, :taurus, :gemini, :cancer, :leo, :virgo, :libra,
                    :scorpio, :sagittarius, :capricorn, :aquarius, :pisces ]
  enum ethnicity: [ :Asian, :Black, :Caucasian, :Hispanic ]

  def geocode_string
    "#{city}, #{country}"
  end

  def height_feet
    height ? feet_and_inches(height)[0] : ""
  end

  def height_inches
    height ? feet_and_inches(height)[1] : ""
  end

  private
  def set_profile_image
    response = HTTParty.get("http://api.randomuser.me/?gender=#{customer.gender}")
    punter_info = JSON(response.body)
    images = punter_info["results"][0]["user"]["picture"]
    self.img_url = images["medium"]
    self.thumb_url = images["thumbnail"]
  end
end

app/models/profile_language.rb
class ProfileLanguage < ActiveRecord::Base
  belongs_to :language
  belongs_to :profile

  accepts_nested_attributes_for :language
end

app/models/religion.rb
class Religion < ActiveRecord::Base

  has_many :profiles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    profile_path(resource.profile) || root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :first_name, :last_name, :type, :date_of_birth, :username) }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :find_message, only: [ :show, :new_reply]

  def new_reply
    @message_reply = Message.new
  end

  def create
    id = params[:message][:responds_to_id]
    @message = Message.find(id)

    @message_reply = Message.new(message_params)
    @message_reply.assign_attributes(sender: @message.recipient, recipient: @message.sender, responds_to: @message)
    @message_reply.save!

    redirect_to messages_path
  end

  def index
    @messages = Message.where(:recipient_id => current_customer.id).order('created_at DESC')
  end

  def show
    @message.update!(read: true)
  end

  private
  def find_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:subject, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_filter :find_profile, :only => [:show, :edit, :update]

  def index
    @profiles = Profile.all
  end

  def edit
    @religion_options = Religion.pluck(:name, :id).prepend(["", 0])
  end

  def add_language
    @language = Language.new
  end

  def search
    @customers = Customer.where(type: current_customer.gender_pref)
    @profiles = Profile.joins(:customer).where("customers.type = ?", current_customer.gender_pref)


    unless params[:industry].empty?
      @profiles = @profiles.where(industry: params[:industry])
    end

    unless params[:ethnicity].empty?
      @profiles = @profiles.where(ethnicity: params[:ethnicity])
    end

    unless params[:distance].empty?
      @profiles = @profiles.near([current_customer.profile.longitude, current_customer.profile.latitude], params[:distance])
    end

    @profiles = @profiles.where("age >= ?", params[:min_age]) unless params[:min_age].empty?
    @profiles = @profiles.where("age <= ?", params[:max_age]) unless params[:max_age].empty?

  end

  def update
    @profile.update!(profile_params)
    redirect_to root_path
  end

  def height
    @form = params[:form]
    @measurement = params[:measurement]
  end

  private
  def profile_params
    params.require(:profile).permit(:biography, :education, :smoker, :religion_id,
                                    :drinks, :height, :height_feet, :height_inches, :star_sign,
                                    :profile_languages_attributes => [:id, :language_attributes =>[:id, :name]])
  end

  def find_profile
    @profile = Profile.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  protected
  def after_sign_up_path_for(resource)
    
    if resource.type == "Female"
      profile_path(resource.profile)
    else
      new_subscriber_path
    end
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_filter :authenticate_customer!
  def new
  end

  def create

    begin

    customer = Stripe::Customer.create(
      :email   => params[:stripeEmail],
      :source  => params[:stripeToken],
      :plan    => 1
    )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
    current_customer.update!(:subscriber => true)
    redirect_to profile_path(current_customer.profile)
      flash[:notice] = "Thanks for joining WeGotSingles as a Gold Member"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wegotsingles</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>

    <a href="<%= root_path %>">
		  <i id="main-logo"><span id="site-title">We Got Singles</span></i>
    </a>

    <% if current_customer %>
      <div id='mail-link'>
        <% unless current_customer.received_messages.where(read: nil).empty? %>
          <div id='new-messages'>
            <%= current_customer.received_messages.where(read: nil).count %>
          </div>
        <% end %>
        <a id="message-a-tag" href="<%= messages_path %>"><%= image_tag 'mail.png' %></a>
      </div>
    <% end %>

    <ul id="full-menu">
        <li><%= link_to 'Search', profiles_path %></li>
        <% if current_customer %>
          <li><%= link_to 'My Profile', profile_path(current_customer.profile) %></li>
          <li><%= link_to 'Log Out', destroy_customer_session_path, method: 'DELETE' %></li>
        <% else %>
          <li><%= link_to 'Register', new_customer_registration_path %></li>
          <li><%= link_to 'Log In', new_customer_session_path %></li>
        <% end %>
      </ul>

    <%= image_tag "hamburger.png", id: "hamburger" %>
    <div id="mobile-menu">
      <ul>
        <li><%= link_to 'Search', profiles_path %></li>
        <% if current_customer %>
          <li><%= link_to 'My Profile', profile_path(current_customer.profile) %></li>
          <li><%= link_to 'Log Out', destroy_customer_session_path, method: 'DELETE' %></li>
        <% else %>
          <li><%= link_to 'Register', new_customer_registration_path %></li>
          <li><%= link_to 'Log In', new_customer_session_path %></li>
        <% end %>
      </ul>
    </div>

	</header>

	<main>

    <%= yield %>

	</main>

  <footer>
    &#169; 2015 We Got Coders
  </footer>

</body>
</html>

app/views/layouts/subscribers.html.haml
<!DOCTYPE html>
%html
%head
  %title Document
%body
  = yield
  

app/views/messages/index.html.haml
%h1 This is your inbox
%section#inbox
  %h1 Your received messages
  - @messages.each do |message|
    .inbox-message
      - unless message.read
        %strong= link_to message.subject, message_path(message), class: 'message-subject'
      - else
        = link_to message.subject, message_path(message), class: 'message-subject'
      %span.message-sender
        From: #{message.sender.first_name} #{message.sender.last_name}
      - unless message.read
        %i.unread Unread

app/views/messages/new_reply.html.haml
%h1 Reply to the message #{ @message.subject }
%h2 From : #{ @message.recipient.email }
%h2 To: #{ @message.sender.email }

= form_for @message_reply do |f|

  = f.label :subject
  = f.text_field :subject

  = f.label :body
  = f.text_field :body

  = f.hidden_field :responds_to_id, value: "#{@message.id}"
  = f.submit :send

app/views/messages/show.html.haml
%section.message
  %h1
    Message from #{@message.sender.username}
  %span
    = link_to "Reply", new_reply_message_path(@message)
  %h2
    Subject:
    %span.subject
      = @message.subject
  %p
    = @message.body

app/views/notifier/new_message.html.erb
<h1>Someone has sent you a message!</h1>

<p>Hi <%= @recipient.first_name %>!</p>

<p>You've received a new message from <%= @sender.username %>. Please follow the link below to view it.</p>

<p><a href="<%= message_path(@message) %>"></a></p>

app/views/notifier/new_message.text.erb
Someone has sent you a message!

Hi #{@recipient.first_name}!

You've received a new message from #{@sender.username}. Please follow the link below to view it.

<%= message_path(@message) %>

app/views/pages/home.html.haml
#main-container
  %h1
    Welcome to We Got Singles

  %h2


  %a.btn.btn-positive{ href: new_customer_registration_path }
    Sign up now!

app/views/profiles/_profile.html.haml
.profile-container
  %h2 #{profile.customer.username}

  %img.profile-photo{:src => profile.img_url, :alt => "Profile picture of member #{profile.customer.first_name}"}

  %dl
    %dt
      Name
    %dd
      = "#{profile.customer.first_name} #{profile.customer.last_name}"

    %dt
      Age
    %dd
      = profile.age

    %dt
      Gender
    %dd
      = profile.customer.type

    %dt
      Languages
    - profile.languages.each do |language|
      %dd
        = language.name

    %dt
      Religion
    %dd
      = profile.religion.name if profile.religion

    %dt
      Education
    %dd
      = profile.education

    %dt
      Height
    %dd
      = "#{profile.height}cm"

    %dt
      Star Sign
    %dd
      = profile.star_sign

    %dt
      Drinking Preferences
    %dd
      = profile.drinks

app/views/profiles/add_language.js.erb
console.log(i);
$("#language_field").append("<input type='text' name='profile[profile_languages_attributes][" + i + "][language_attributes][name]' id='profile_profile_languages_attributes_" + i + "_language_attributes_name' class='language_input'>")
i++;

app/views/profiles/edit.html.haml
= form_for @profile do |f|
  %fieldset
    = f.label :biography
    = f.text_field :biography
  %fieldset
    = f.label :education
    = f.select :education, Profile.educations.keys.to_a, include_blank: true, selected: @profile.education
  %fieldset
    = f.label :star_sign, "Star Sign"
    = f.select :star_sign, Profile.star_signs.keys.to_a, include_blank: true, selected: @profile.star_sign
  %fieldset
    = f.label :religion_id, "Religion"
    = f.select :religion_id, options_for_select(@religion_options, "#{@profile.religion.id if @profile.religion}")
  %fieldset
    = label_tag :industry
    = select_tag :industry, options_for_select([['Medicine', 'Medicine'], ['Computing', 'Computing']]), include_blank: true
  %fieldset
    = f.label :smoker
    = f.check_box :smoker

  %fieldset#language_field
    = label :profile_languages, "Languages"
    = f.fields_for :profile_languages do |pl|
      = pl.fields_for :language do |l|
        = l.text_field :name, :class => "language_input"
  = link_to "Add Language", add_language_profile_path(@profile), :remote => true
  %fieldset
    = label_tag "measurement_Centimetres", "Centimetres"
    = radio_button_tag "measurement", "Centimetres", true, id: "cm_button"
    = label_tag "measurement_Feet_and_Inches", "Feet and Inches"
    = radio_button_tag "measurement", "Feet and Inches", false,  id: "ft_button"
  #measurements
    #cm
      = f.label :height, "Height(cm)"
      = f.number_field :height, in: 50..275
    #feet
      = f.label :height_feet, "Height(ft)"
      = f.number_field :height_feet
    #inches
      = f.label :height_inches, "Height(in)"
      = f.number_field :height_inches
  %fieldset
    = f.label :drinks
    = f.select :drinks, Profile.drinks.keys.to_a, include_blank: true, selected: nil
  %fieldset
    = f.submit :Submit

:javascript
  console.log($(".language_input").length);
  var i = $(".language_input").length;

app/views/profiles/height.js.erb
<% if @measurement == "cm" %>
  $('#height').html("<input  min='50' max='275' type='number' id='profile_height' value='<%= self.height_feet  %>' name='profile[height]'>");
<% else %>
  $('#height').html("<input min='1' max='9' type='number' id='feet' value='<%= self.height_inches  %>' name='feet'>")
  $('#height').append("<input min='0' max='12' type='number' id='inches' name='inches'>")
<% end %>

app/views/profiles/index.html.haml
#search
  = form_tag search_profiles_path, method: "GET", remote: true do
    %fieldset
      = label_tag :gender
      = select_tag :gender, options_for_select([['male', 'male'], ['female', 'female']]),include_blank: true
    %fieldset
      = label_tag :industry
      = select_tag :industry, options_for_select([['Medicine', 'Medicine'], ['Computing', 'Computing']]), include_blank: true
    %fieldset
      = label_tag :ethnicity
      = select_tag :ethnicity, options_for_select(Profile.ethnicities.keys), include_blank: true
    %fieldset
      = label_tag :distance
      = select_tag :distance, options_for_select([['5km', '5'], ['10km', '10'], ['20km', '20'], ['50km', '50']]), include_blank: true
    %fieldset
      = label_tag "Min age"
      = select_tag :min_age, options_for_select((18..130).to_a.map{|s| ["#{s}", s]}), include_blank: true
      = label_tag "Max age"
      = select_tag :max_age, options_for_select((18..130).to_a.map{|s| ["#{s}", s]}), include_blank: true
    %fieldset
      = label_tag :drinks
      = select_tag :drinks, options_for_select(Profile.drinks.keys.to_a), include_blank: true
    %fieldset
      = submit_tag :search
#results
  - @profiles.each do |profile|
    = render profile

app/views/profiles/search.js.erb
$('#results').html("<% @profiles.each do |profile| %><%= j render profile %><% end %>");

app/views/profiles/show.html.haml
- if current_customer == @profile.customer
  %h3#completedness-text Your profile is #{@profile.profile_completed}% complete
  %progress.progress-bar{:value => @profile.profile_completed, :max => "100"}

= render @profile

app/views/subscribers/create.html.erb
<h2>Thanks for joining WeGotSingles as a Gold Member </h2>
<p> You can now reply to message and send message to other members</p>

app/views/subscribers/new.html.erb
<%= form_tag subscribers_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <h2> Thanks for choosing to become a premium member </h2>
    <label class="amount">
      <span>Amount: £9.99</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="999"
          data-locale="auto"></script>
<% end %>

  <h2>Or view all profiles</h2>
  <%= link_to "View all profiles", profiles_path %> 